apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: eskxupnmh-go 
  janus-idp.io/tekton: eskxupnmh-go
  backstage.io/kubernetes-id: eskxupnmh-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: eskxupnmh-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml